name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.0.1
  - ipython=8.7.0
  - notebook=6.5.2
  - jupyterlab=3.5.2
  - cookiecutter=2.1.1
  - hydra-core=1.3.1
  - matplotlib=3.6.2
  - pandas=1.5.2
  - git=2.39.0
  - pip=22.3.1
  - pip:
      - wandb==0.13.7
