name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.2
  - pip=22.3.1
  - mlflow=2.0.1
  - scikit-learn=1.2.0
  - pip:
      - wandb==0.13.7
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
