name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.2
  - pip=22.3.1
  - mlflow=2.0.1
  - scikit-learn=1.2.0
  - matplotlib=3.6.2
  - pillow=9.4.0
  - pip:
      - wandb==0.13.7
